server:
  port: 8000

spring:
  redis:
#    cluster:
#      nodes: 127.0.0.1:6379,127.0.0.1:6379
    database: 1
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 100
        max-wait: -1s
        max-active: 1000
